services:
  app:
    command: sh -c "yarn install && yarn start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # keep container's node_modules
    environment:
      NODE_ENV: development

  pgadmin:
    image: dpage/pgadmin4
    container_name: monolingo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
